import PERMISSIONS from './permissions'

export const ROLE_PERMISSIONS: Record<string, string[]> = {

    // ── Super Admin: everything ───────────────────────────────────────────────
    super_admin: Object.values(PERMISSIONS),

    // ── Admin: full access except audit logs ──────────────────────────────────
    admin: [
        PERMISSIONS.DASHBOARD_VIEW,

        PERMISSIONS.USER_CREATE, PERMISSIONS.USER_VIEW, PERMISSIONS.USER_UPDATE, PERMISSIONS.USER_DELETE,

        PERMISSIONS.EMPLOYEE_CREATE, PERMISSIONS.EMPLOYEE_VIEW, PERMISSIONS.EMPLOYEE_UPDATE, PERMISSIONS.EMPLOYEE_DELETE,
        PERMISSIONS.DEPARTMENT_CREATE, PERMISSIONS.DEPARTMENT_VIEW, PERMISSIONS.DEPARTMENT_UPDATE, PERMISSIONS.DEPARTMENT_DELETE,
        PERMISSIONS.POSITION_CREATE, PERMISSIONS.POSITION_VIEW, PERMISSIONS.POSITION_UPDATE, PERMISSIONS.POSITION_DELETE,

        PERMISSIONS.ATTENDANCE_CREATE, PERMISSIONS.ATTENDANCE_VIEW, PERMISSIONS.ATTENDANCE_UPDATE, PERMISSIONS.ATTENDANCE_CHECKIN, PERMISSIONS.ATTENDANCE_CHECKOUT,
        PERMISSIONS.LEAVE_CREATE, PERMISSIONS.LEAVE_VIEW, PERMISSIONS.LEAVE_UPDATE, PERMISSIONS.LEAVE_APPROVE, PERMISSIONS.LEAVE_REJECT, PERMISSIONS.LEAVE_VOID,
        PERMISSIONS.LEAVETYPE_CREATE, PERMISSIONS.LEAVETYPE_VIEW, PERMISSIONS.LEAVETYPE_UPDATE, PERMISSIONS.LEAVETYPE_DEACTIVATE,
        PERMISSIONS.OVERTIME_CREATE, PERMISSIONS.OVERTIME_VIEW, PERMISSIONS.OVERTIME_UPDATE, PERMISSIONS.OVERTIME_VOID,
        PERMISSIONS.SHIFT_CREATE, PERMISSIONS.SHIFT_VIEW, PERMISSIONS.SHIFT_UPDATE, PERMISSIONS.SHIFT_DEACTIVATE,

        PERMISSIONS.PAYROLL_RUN, PERMISSIONS.PAYROLL_VIEW, PERMISSIONS.PAYROLL_APPROVE, PERMISSIONS.PAYROLL_REJECT, PERMISSIONS.PAYROLL_FINALIZE,
        PERMISSIONS.SALARY_CREATE, PERMISSIONS.SALARY_VIEW, PERMISSIONS.SALARY_UPDATE, PERMISSIONS.SALARY_DELETE,
        PERMISSIONS.SALARYCOMPONENT_CREATE, PERMISSIONS.SALARYCOMPONENT_VIEW, PERMISSIONS.SALARYCOMPONENT_UPDATE, PERMISSIONS.SALARYCOMPONENT_DELETE,
        PERMISSIONS.PAYGRADE_CREATE, PERMISSIONS.PAYGRADE_VIEW, PERMISSIONS.PAYGRADE_UPDATE, PERMISSIONS.PAYGRADE_DELETE,
        PERMISSIONS.DEDUCTION_CREATE, PERMISSIONS.DEDUCTION_VIEW, PERMISSIONS.DEDUCTION_UPDATE, PERMISSIONS.DEDUCTION_VOID,

        PERMISSIONS.REWARD_CREATE, PERMISSIONS.REWARD_VIEW, PERMISSIONS.REWARD_UPDATE, PERMISSIONS.REWARD_VOID,
        PERMISSIONS.PUNISHMENT_CREATE, PERMISSIONS.PUNISHMENT_VIEW, PERMISSIONS.PUNISHMENT_UPDATE, PERMISSIONS.PUNISHMENT_VOID,

        PERMISSIONS.AUDITLOG_VIEW,
        PERMISSIONS.SELF_VIEW,
    ],

    
    hr_manager: [
        PERMISSIONS.DASHBOARD_VIEW,
        PERMISSIONS.EMPLOYEE_VIEW,
        PERMISSIONS.DEPARTMENT_VIEW,
        PERMISSIONS.POSITION_VIEW,
        PERMISSIONS.ATTENDANCE_VIEW, PERMISSIONS.ATTENDANCE_CREATE, PERMISSIONS.ATTENDANCE_UPDATE,
        PERMISSIONS.LEAVE_CREATE, PERMISSIONS.LEAVE_VIEW, PERMISSIONS.LEAVE_UPDATE, PERMISSIONS.LEAVE_APPROVE, PERMISSIONS.LEAVE_REJECT, PERMISSIONS.LEAVE_VOID,
        PERMISSIONS.LEAVETYPE_CREATE, PERMISSIONS.LEAVETYPE_VIEW, PERMISSIONS.LEAVETYPE_UPDATE, PERMISSIONS.LEAVETYPE_DEACTIVATE,
        PERMISSIONS.OVERTIME_VIEW, PERMISSIONS.OVERTIME_CREATE, PERMISSIONS.OVERTIME_UPDATE, PERMISSIONS.OVERTIME_VOID,
        PERMISSIONS.SHIFT_VIEW,
        PERMISSIONS.REWARD_CREATE, PERMISSIONS.REWARD_VIEW, PERMISSIONS.REWARD_UPDATE, PERMISSIONS.REWARD_VOID,
        PERMISSIONS.PUNISHMENT_CREATE, PERMISSIONS.PUNISHMENT_VIEW, PERMISSIONS.PUNISHMENT_UPDATE, PERMISSIONS.PUNISHMENT_VOID,
        PERMISSIONS.SELF_VIEW,
    ],

    
    hr: [
        PERMISSIONS.DASHBOARD_VIEW,
        PERMISSIONS.EMPLOYEE_VIEW,
        PERMISSIONS.LEAVE_VIEW, PERMISSIONS.LEAVE_APPROVE, PERMISSIONS.LEAVE_REJECT,
        PERMISSIONS.ATTENDANCE_VIEW,
        PERMISSIONS.SELF_VIEW,
    ],

    
    payroll_manager: [
        PERMISSIONS.DASHBOARD_VIEW,
        PERMISSIONS.EMPLOYEE_VIEW,
        PERMISSIONS.PAYROLL_RUN, PERMISSIONS.PAYROLL_VIEW, PERMISSIONS.PAYROLL_APPROVE, PERMISSIONS.PAYROLL_REJECT, PERMISSIONS.PAYROLL_FINALIZE,
        PERMISSIONS.SALARY_CREATE, PERMISSIONS.SALARY_VIEW, PERMISSIONS.SALARY_UPDATE, PERMISSIONS.SALARY_DELETE,
        PERMISSIONS.SALARYCOMPONENT_CREATE, PERMISSIONS.SALARYCOMPONENT_VIEW, PERMISSIONS.SALARYCOMPONENT_UPDATE, PERMISSIONS.SALARYCOMPONENT_DELETE,
        PERMISSIONS.PAYGRADE_CREATE, PERMISSIONS.PAYGRADE_VIEW, PERMISSIONS.PAYGRADE_UPDATE, PERMISSIONS.PAYGRADE_DELETE,
        PERMISSIONS.DEDUCTION_CREATE, PERMISSIONS.DEDUCTION_VIEW, PERMISSIONS.DEDUCTION_UPDATE, PERMISSIONS.DEDUCTION_VOID,
        PERMISSIONS.SELF_VIEW,
    ],

    
    leave_manager: [
        PERMISSIONS.DASHBOARD_VIEW,
        PERMISSIONS.LEAVE_CREATE, PERMISSIONS.LEAVE_VIEW, PERMISSIONS.LEAVE_UPDATE, PERMISSIONS.LEAVE_APPROVE, PERMISSIONS.LEAVE_REJECT, PERMISSIONS.LEAVE_VOID,
        PERMISSIONS.LEAVETYPE_CREATE, PERMISSIONS.LEAVETYPE_VIEW, PERMISSIONS.LEAVETYPE_UPDATE, PERMISSIONS.LEAVETYPE_DEACTIVATE,
        PERMISSIONS.ATTENDANCE_VIEW,
        PERMISSIONS.SELF_VIEW,
    ],

    
    overtime_manager: [
        PERMISSIONS.DASHBOARD_VIEW,
        PERMISSIONS.OVERTIME_CREATE, PERMISSIONS.OVERTIME_VIEW, PERMISSIONS.OVERTIME_UPDATE, PERMISSIONS.OVERTIME_VOID,
        PERMISSIONS.ATTENDANCE_VIEW,
        PERMISSIONS.SELF_VIEW,
    ],

    
    punishment_manager: [
        PERMISSIONS.DASHBOARD_VIEW,
        PERMISSIONS.PUNISHMENT_CREATE, PERMISSIONS.PUNISHMENT_VIEW, PERMISSIONS.PUNISHMENT_UPDATE, PERMISSIONS.PUNISHMENT_VOID,
        PERMISSIONS.EMPLOYEE_VIEW,
        PERMISSIONS.SELF_VIEW,
    ],

    // ── Employee: self-service only ───────────────────────────────────────────
    employee: [
        PERMISSIONS.DASHBOARD_VIEW,
        PERMISSIONS.SELF_VIEW,
        PERMISSIONS.ATTENDANCE_CHECKIN,
        PERMISSIONS.ATTENDANCE_VIEW,
        PERMISSIONS.ATTENDANCE_CHECKOUT,
    ],
}