import { PERMISSIONS } from "./permissions.js";

export const ROLE_PERMISSIONS = {
    super_admin: Object.values(PERMISSIONS),

    admin: [
        PERMISSIONS.USER_CREATE,
        PERMISSIONS.USER_VIEW,
        PERMISSIONS.USER_UPDATE,
        PERMISSIONS.USER_DELETE,

        PERMISSIONS.EMPLOYEE_CREATE,
        PERMISSIONS.EMPLOYEE_VIEW,
        PERMISSIONS.EMPLOYEE_UPDATE,
        PERMISSIONS.EMPLOYEE_DELETE,

        PERMISSIONS.DEPARTMENT_CREATE,
        PERMISSIONS.DEPARTMENT_VIEW,
        PERMISSIONS.DEPARTMENT_UPDATE,
        PERMISSIONS.DEPARTMENT_DELETE,

        PERMISSIONS.POSITION_CREATE,
        PERMISSIONS.POSITION_VIEW,
        PERMISSIONS.POSITION_UPDATE,
        PERMISSIONS.POSITION_DELETE,

        PERMISSIONS.PAYROLL_VIEW,
        PERMISSIONS.SELF_VIEW,

        PERMISSIONS.ATTENDANCE_CREATE,
        PERMISSIONS.ATTENDANCE_VIEW,
        PERMISSIONS.ATTENDANCE_UPDATE,

        PERMISSIONS.AUDITLOG_VIEW,
        PERMISSIONS.DASHBOARD_VIEW,

        PERMISSIONS.SHIFT_CREATE,
        PERMISSIONS.SHIFT_VIEW,
        PERMISSIONS.SHIFT_UPDATE,
        PERMISSIONS.SHIFT_DELETE,

        PERMISSIONS.HOLIDAY_CREATE,
        PERMISSIONS.HOLIDAY_VIEW,
        PERMISSIONS.HOLIDAY_UPDATE,
        PERMISSIONS.HOLIDAY_DELETE,

        PERMISSIONS.DOCUMENT_CREATE,
        PERMISSIONS.DOCUMENT_VIEW,
        PERMISSIONS.DOCUMENT_DELETE,

        PERMISSIONS.SETTINGS_VIEW,
        PERMISSIONS.SETTINGS_UPDATE,

        PERMISSIONS.LEAVE_VIEW,
        PERMISSIONS.LEAVE_APPROVE,
        PERMISSIONS.LEAVE_REJECT,
        PERMISSIONS.LEAVETYPE_VIEW,
    ],

    hr_manager: [
        PERMISSIONS.EMPLOYEE_CREATE,
        PERMISSIONS.EMPLOYEE_VIEW,
        PERMISSIONS.EMPLOYEE_UPDATE,
        PERMISSIONS.EMPLOYEE_DELETE,

        PERMISSIONS.DEPARTMENT_CREATE,
        PERMISSIONS.DEPARTMENT_VIEW,
        PERMISSIONS.DEPARTMENT_UPDATE,
        PERMISSIONS.DEPARTMENT_DELETE,

        PERMISSIONS.POSITION_CREATE,
        PERMISSIONS.POSITION_VIEW,
        PERMISSIONS.POSITION_UPDATE,
        PERMISSIONS.POSITION_DELETE,

        PERMISSIONS.PUNISHMENT_CREATE,
        PERMISSIONS.PUNISHMENT_VIEW,
        PERMISSIONS.PUNISHMENT_UPDATE,
        PERMISSIONS.PUNISHMENT_VOID,

        PERMISSIONS.REWARD_CREATE,
        PERMISSIONS.REWARD_VIEW,
        PERMISSIONS.REWARD_UPDATE,
        PERMISSIONS.REWARD_VOID,

        PERMISSIONS.PAYGRADE_VIEW,
        PERMISSIONS.SELF_VIEW,

        PERMISSIONS.ATTENDANCE_CREATE,
        PERMISSIONS.ATTENDANCE_VIEW,
        PERMISSIONS.ATTENDANCE_UPDATE,

        PERMISSIONS.HOLIDAY_CREATE,
        PERMISSIONS.HOLIDAY_VIEW,
        PERMISSIONS.HOLIDAY_UPDATE,
        PERMISSIONS.HOLIDAY_DELETE,

        PERMISSIONS.DOCUMENT_DELETE,

        PERMISSIONS.DASHBOARD_VIEW,

        PERMISSIONS.LEAVE_VIEW,
        PERMISSIONS.LEAVE_APPROVE,
        PERMISSIONS.LEAVE_REJECT,
        PERMISSIONS.LEAVETYPE_VIEW,
    ],

    payroll_manager: [
        PERMISSIONS.PAYROLL_RUN,
        PERMISSIONS.PAYROLL_APPROVE,
        PERMISSIONS.PAYROLL_REJECT,
        PERMISSIONS.PAYROLL_FINALIZE,
        PERMISSIONS.PAYROLL_VIEW,

        PERMISSIONS.DEDUCTION_CREATE,
        PERMISSIONS.DEDUCTION_VIEW,
        PERMISSIONS.DEDUCTION_UPDATE,
        PERMISSIONS.DEDUCTION_VOID,

        PERMISSIONS.SALARY_CREATE,
        PERMISSIONS.SALARY_VIEW,
        PERMISSIONS.SALARY_UPDATE,
        PERMISSIONS.SALARY_DELETE,

        PERMISSIONS.SALARYCOMPONENT_CREATE,
        PERMISSIONS.SALARYCOMPONENT_VIEW,
        PERMISSIONS.SALARYCOMPONENT_UPDATE,
        PERMISSIONS.SALARYCOMPONENT_DELETE,

        PERMISSIONS.PAYGRADE_CREATE,
        PERMISSIONS.PAYGRADE_VIEW,
        PERMISSIONS.PAYGRADE_UPDATE,

        PERMISSIONS.REWARD_VIEW,
        PERMISSIONS.PUNISHMENT_VIEW,
        PERMISSIONS.SELF_VIEW,

        PERMISSIONS.DASHBOARD_VIEW
    ],

    overtime_manager: [
        PERMISSIONS.OVERTIME_CREATE,
        PERMISSIONS.OVERTIME_VIEW,
        PERMISSIONS.OVERTIME_UPDATE,
        PERMISSIONS.OVERTIME_VOID,
        PERMISSIONS.SELF_VIEW,

        PERMISSIONS.DASHBOARD_VIEW
    ],

    punishment_manager: [
        PERMISSIONS.PUNISHMENT_CREATE,
        PERMISSIONS.PUNISHMENT_VIEW,
        PERMISSIONS.PUNISHMENT_UPDATE,
        PERMISSIONS.PUNISHMENT_VOID,
        PERMISSIONS.SELF_VIEW,

        PERMISSIONS.DASHBOARD_VIEW
    ],

    employee: [
        PERMISSIONS.SELF_VIEW,
        PERMISSIONS.ATTENDANCE_CHECKIN,
        PERMISSIONS.ATTENDANCE_CHECKOUT,
        PERMISSIONS.LEAVE_VIEW,
        PERMISSIONS.LEAVE_CREATE,
        PERMISSIONS.LEAVETYPE_VIEW,
    ]
};